name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Running test in Python"
        run: |
          echo "[** VERSION PYTHON: $(python --version) **]"
          ./tests/setup
          python -m pytest -v --import-mode=append tests/
