name: Parallel Testing

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9] #Todas las definiciones a este nivel tienen que tener la misma cantidad de elementos
        # node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Comprobación de versión de Python
        run: |
              echo "::notice:: **#-- VERSION PYTHON: $(python --version) --#**"

      - name: Setup previo para pruebas
        run: |
              ./tests/setup
      
      - name: Ejecución de pruebas
        run: |
              python -m pytest -v --import-mode=append tests/ --html=reports/${{ matrix.python-version }}/report.html
      
      - name: Subir directorio
        uses: actions/upload-artifact@v3
        with:
          name: reportes
          path: reports/

  publish-report:
    runs-on: ubuntu-latest
    steps:
      - name: Download report
        uses: actions/download-artifact@v3
        with:
          name: reportes
          path: python-reports/

      - name: Mostrar reportes
        run: |
              tree python-reports/